### ISSUE TITLE
lxd.migrate hangs when uninstalling old LXD

### ISSUE THREAD

**Issue by relaxdiego** [lxc/lxd-pkg-ubuntu#36] opened 2019-05-24 02:50 UTC
# Required information

 * Distribution: 

Ubuntu

 * Distribution version:

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

 * The output of "lxc info":

```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICBTCCAYqgAwIBAgIRAL/a/bY+LXX57uGU9FnKpQkwCgYIKoZIzj0EAwMwOjEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEaMBgGA1UEAwwRcm9vdEBub2Rl
    LWNhbG9yaWMwHhcNMTkwNTI0MDEyODMzWhcNMjkwNTIxMDEyODMzWjA6MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRowGAYDVQQDDBFyb290QG5vZGUtY2Fs
    b3JpYzB2MBAGByqGSM49AgEGBSuBBAAiA2IABCG5aqQxfpRnLJKL58wUgdQiE3t3
    uzuKrxBqou3I0sojeWD8uK2fMgqtgH/URDIbfGrS4v4kpYcGgxV1wTJt0ZwFQYS8
    WlmeNo1tVnWadCSDhBGomWrQI0Fsp42NsvZDpaNUMFIwDgYDVR0PAQH/BAQDAgWg
    MBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYDVR0RBBYwFIIM
    bm9kZS1jYWxvcmljhwQK9ag4MAoGCCqGSM49BAMDA2kAMGYCMQClcYSYY2Jw8eeW
    7DgdOOueVbNaqkxulKYlI2O9VmAN4VR9dAdG9RSDBTjXI4ZbNVsCMQDYYykojAFf
    P4QJuGZHBwPTlxVMhsjYeiGFF2etQga/GEu3qUe9YzG0EF9CMYE9kv8=
    -----END CERTIFICATE-----
  certificate_fingerprint: 264560f4473b23bbbee650c83a060ecb7a58af552338c1d5c4c28b374b4b5c23
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-50-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "false"
    network_ipvlan: "false"
    network_l2proxy: "false"
    seccomp_notify: "false"
  project: default
  server: lxd
  server_clustered: false
  server_name: node-caloric
  server_pid: 828
  server_version: "3.13"
  storage: ""
  storage_version: ""
```

   * Storage backend in use:

N/A - Haven't started lxd init yet. Just migrating.

# Issue description

On a fresh install of Ubuntu 18.04, whenever I run lxd.migrate and choose yes to the question `Do you want to uninstall the old LXD?`, the step hangs or takes an inordinate amount of time. Checking the process and logs show:

```
~# ps -aux | grep apt | grep -v grep
root     32517  0.9  0.1 108580 59100 pts/1    S+   01:28   0:00 apt-get remove --purge --yes lxd lxd-client

~# tail -f /var/log/apt/term.log
Setting up python3-update-manager (1:18.04.11.10) ...
Setting up python3-distupgrade (1:18.04.33) ...
Setting up ubuntu-release-upgrader-core (1:18.04.33) ...
Setting up update-manager-core (1:18.04.11.10) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Log ended: 2019-05-24  01:23:52

Log started: 2019-05-24  01:28:41
(Reading database ... 66953 files and directories currently installed.)
Removing lxd (3.0.3-0ubuntu1~18.04.1) ...
^C
```

However, when I choose no and then run that command myself, the command completes succesfully:

```
~$ sudo apt-get remove --purge --yes lxd lxd-client
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libuv1
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
  lxd* lxd-client*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 31.7 MB disk space will be freed.
(Reading database ... 66953 files and directories currently installed.)
Removing lxd (3.0.3-0ubuntu1~18.04.1) ...
Removing lxd dnsmasq configuration
Removing lxd-client (3.0.3-0ubuntu1~18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
(Reading database ... 66779 files and directories currently installed.)
Purging configuration files for lxd (3.0.3-0ubuntu1~18.04.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
ureadahead will be reprofiled on next reboot
Processing triggers for systemd (237-3ubuntu10.21) ...


ubuntu@node-caloric:~$ tail -n 15 /var/log/apt/term.log
Log started: 2019-05-24  02:31:44
(Reading database ... 66953 files and directories currently installed.)
Removing lxd (3.0.3-0ubuntu1~18.04.1) ...
Removing lxd dnsmasq configuration
Removing lxd-client (3.0.3-0ubuntu1~18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
(Reading database ... 66779 files and directories currently installed.)
Purging configuration files for lxd (3.0.3-0ubuntu1~18.04.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
ureadahead will be reprofiled on next reboot
Processing triggers for systemd (237-3ubuntu10.21) ...
Log ended: 2019-05-24  02:31:51
```

# Steps to reproduce

```
~$ sudo apt update
~$ sudo apt upgrade -y
~$ byobu-enable
~$ wget -O ~/.byobu/keybindings.tmux https://gist.githubusercontent.com/relaxdiego/bda8694d38f4c635eee40d15bec3e73e/raw/byobu-keybindings.tmux
~$ byobu
~$ sudo snap install lxd
~$ sudo lxd.migrate
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks
The source server is empty, no migration needed.

The migration is now complete and your containers should be back online.
Do you want to uninstall the old LXD (yes/no) [default=yes]?  <Enter>
```

**Comment by stgraber** [comment] 2019-05-24 02:54
Can you show `ps fauxww`?

We have daily testing of this in place so it's unlikely to be as simple as 18.04 + snap + lxd.migrate.

**Comment by relaxdiego** [comment] 2019-05-24 05:12
Weird. This has happened to me twice before but now that I tried it again on a freshly installed machine:

```
ubuntu@node-couder:~$ sudo lxd.migrate
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks
The source server is empty, no migration needed.

The migration is now complete and your containers should be back online.
Do you want to uninstall the old LXD (yes/no) [default=yes]?

All done. You may need to close your current shell and open a new one to have the "lxc" command work.
To migrate your existing client configuration, move ~/.config/lxc to ~/snap/lxd/current/.config/lxc
```

**Comment by davigar15** [comment] 2020-03-30 10:20
This is happening to me. Not always, but very frequently.:

```
ubuntu@osm-1:~$ ps -aux | grep apt | grep -v grep
root      5317  0.3  0.7 119256 62464 pts/0    S+   10:13   0:00 apt-get remove --purge --yes lxd lxd-client
ubuntu@osm-1:~$ tail -f /var/log/apt/term.log
Setting up libjq1:amd64 (1.5+dfsg-2) ...
Setting up git (1:2.17.1-1ubuntu0.5) ...
Setting up jq (1.5+dfsg-2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Log ended: 2020-03-30  10:13:21

Log started: 2020-03-30  10:13:49
(Reading database ... 60734 files and directories currently installed.)
Removing lxd (3.0.3-0ubuntu1~18.04.1) ...
^C
ubuntu@osm-1:~$ ps fauxww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         2  0.0  0.0      0     0 ?        S    10:07   0:00 [kthreadd]
root         4  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [kworker/0:0H]
root         5  0.0  0.0      0     0 ?        I    10:07   0:00  \_ [kworker/u4:0]
root         6  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [mm_percpu_wq]
root         7  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [ksoftirqd/0]
root         8  0.0  0.0      0     0 ?        I    10:07   0:00  \_ [rcu_sched]
root         9  0.0  0.0      0     0 ?        I    10:07   0:00  \_ [rcu_bh]
root        10  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [migration/0]
root        11  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [watchdog/0]
root        12  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [cpuhp/0]
root        13  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [cpuhp/1]
root        14  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [watchdog/1]
root        15  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [migration/1]
root        16  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [ksoftirqd/1]
root        18  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [kworker/1:0H]
root        19  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [kdevtmpfs]
root        20  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [netns]
root        21  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [rcu_tasks_kthre]
root        22  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [kauditd]
root        24  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [khungtaskd]
root        25  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [oom_reaper]
root        26  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [writeback]
root        27  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [kcompactd0]
root        28  0.0  0.0      0     0 ?        SN   10:07   0:00  \_ [ksmd]
root        29  0.0  0.0      0     0 ?        SN   10:07   0:00  \_ [khugepaged]
root        30  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [crypto]
root        31  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [kintegrityd]
root        32  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [kblockd]
root        33  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [ata_sff]
root        34  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [md]
root        35  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [edac-poller]
root        36  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [devfreq_wq]
root        37  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [watchdogd]
root        40  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [kswapd0]
root        41  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [kworker/u5:0]
root        42  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [ecryptfs-kthrea]
root        85  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [kthrotld]
root        86  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [acpi_thermal_pm]
root        87  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [scsi_eh_0]
root        88  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [scsi_tmf_0]
root        89  0.0  0.0      0     0 ?        S    10:07   0:00  \_ [scsi_eh_1]
root        90  0.0  0.0      0     0 ?        I<   10:07   0:00  \_ [scsi_tmf_1]
root        91  0.0  0.0      0     0 ?        I    10:07   0:00  \_ [kworker/u4:2]
root        96  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [ipv6_addrconf]
root       105  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [kstrp]
root       122  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [charger_manager]
root       170  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [kworker/1:1H]
root       263  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [raid5wq]
root       311  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [kworker/0:1H]
root       312  0.0  0.0      0     0 ?        S    10:08   0:00  \_ [jbd2/vda1-8]
root       313  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [ext4-rsv-conver]
root       391  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [iscsi_eh]
root       396  0.0  0.0      0     0 ?        I    10:08   0:00  \_ [kworker/1:2]
root       410  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [ib-comp-wq]
root       412  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [ib_mcast]
root       413  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [ib_nl_sa_wq]
root       418  0.0  0.0      0     0 ?        I<   10:08   0:00  \_ [rdma_cm]
root      4500  0.0  0.0      0     0 ?        I    10:13   0:00  \_ [kworker/0:4]
root      4502  0.0  0.0      0     0 ?        I    10:13   0:00  \_ [kworker/0:5]
root      4507  0.0  0.0      0     0 ?        S<   10:13   0:00  \_ [loop0]
root      4706  0.0  0.0      0     0 ?        S<   10:13   0:00  \_ [loop1]
root      5164  0.0  0.0      0     0 ?        I    10:13   0:00  \_ [kworker/1:0]
root      5481  0.0  0.0      0     0 ?        I    10:19   0:00  \_ [kworker/u4:1]
root      5482  0.0  0.0      0     0 ?        I    10:19   0:00  \_ [kworker/u4:3]
root      5483  0.0  0.0      0     0 ?        I    10:19   0:00  \_ [kworker/u4:4]
root         1  0.3  0.1 159908  9164 ?        Ss   10:07   0:02 /sbin/init
root       386  0.0  0.0  94852  8036 ?        S<s  10:08   0:00 /lib/systemd/systemd-journald
root       399  0.0  0.0  97708  1868 ?        Ss   10:08   0:00 /sbin/lvmetad -f
root       404  0.0  0.0  43120  4156 ?        Ss   10:08   0:00 /lib/systemd/systemd-udevd
systemd+   538  0.0  0.0 141928  3392 ?        Ssl  10:08   0:00 /lib/systemd/systemd-timesyncd
systemd+   647  0.0  0.0  80168  6016 ?        Ss   10:08   0:00 /lib/systemd/systemd-networkd
systemd+   669  0.0  0.0  70756  6100 ?        Ss   10:08   0:00 /lib/systemd/systemd-resolved
root       831  0.0  0.0 287996  6736 ?        Ssl  10:08   0:00 /usr/lib/accountsservice/accounts-daemon
root       838  0.0  0.0 110480  3440 ?        Ssl  10:08   0:00 /usr/sbin/irqbalance --foreground
daemon     840  0.0  0.0  28332  2348 ?        Ss   10:08   0:00 /usr/sbin/atd -f
message+   841  0.0  0.0  50096  4428 ?        Ss   10:08   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root       845  0.0  0.0  31748  3196 ?        Ss   10:08   0:00 /usr/sbin/cron -f
syslog     849  0.0  0.0 267272  4380 ?        Ssl  10:08   0:00 /usr/sbin/rsyslogd -n
root       852  0.0  0.0  70564  5944 ?        Ss   10:08   0:00 /lib/systemd/systemd-logind
root       853  0.0  0.0  95540  1608 ?        Ssl  10:08   0:00 /usr/bin/lxcfs /var/lib/lxcfs/
root       857  0.0  0.2 170824 17084 ?        Ssl  10:08   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
root       869  0.0  0.0  16412  2364 ttyS0    Ss+  10:08   0:00 /sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 ttyS0 vt220
root       871  0.0  0.0 291452  7320 ?        Ssl  10:08   0:00 /usr/lib/policykit-1/polkitd --no-debug
root       874  0.0  0.0  14888  1916 tty1     Ss+  10:08   0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux
root       900  0.0  0.2 187676 20088 ?        Ssl  10:08   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
root      1006  0.0  0.0  72296  5784 ?        Ss   10:08   0:00 /usr/sbin/sshd -D
root      1160  0.0  0.0 107984  7176 ?        Ss   10:09   0:00  \_ sshd: ubuntu [priv]
ubuntu    1278  0.0  0.0 108116  4512 ?        S    10:09   0:00  |   \_ sshd: ubuntu@pts/0
ubuntu    1281  0.0  0.0  23244  5280 pts/0    Ss   10:09   0:00  |       \_ -bash
ubuntu    2584  0.0  0.0  13444  3280 pts/0    S+   10:12   0:00  |           \_ /bin/bash ./install_osm.sh -y
ubuntu    3768  0.0  0.0  14368  4236 pts/0    S+   10:13   0:00  |               \_ /bin/bash /usr/share/osm-devops/installers/full_install_osm.sh -R ReleaseSEVEN -r stable -u https://osm-download.etsi.org/repository/osm/debian -D /usr/share/osm-devops -t 7 -y
root      5062  0.0  0.0  68304  4344 pts/0    S+   10:13   0:00  |                   \_ sudo lxd.migrate --yes
root      5063  0.1  0.1 233832 11452 pts/0    Sl+  10:13   0:00  |                       \_ lxd-migrate --yes
root      5317  0.2  0.7 119256 62464 pts/0    S+   10:13   0:00  |                           \_ apt-get remove --purge --yes lxd lxd-client
root      5342  0.0  0.2  31108 16540 pts/1    Ss+  10:13   0:00  |                               \_ /usr/bin/dpkg --status-fd 43 --no-triggers --force-depends --remove lxd:amd64 lxd-client:amd64
root      5343  0.0  0.0   4640   816 pts/1    S+   10:13   0:00  |                                   \_ /bin/sh /var/lib/dpkg/info/lxd.prerm remove
root      5350  0.0  0.0  65376  5584 pts/1    S+   10:13   0:00  |                                       \_ /bin/systemctl stop lxd-containers.service
root      5393  0.0  0.0 107984  7152 ?        Ss   10:17   0:00  \_ sshd: ubuntu [priv]
ubuntu    5463  0.0  0.0 107984  3680 ?        S    10:17   0:00      \_ sshd: ubuntu@pts/2
ubuntu    5464  0.0  0.0  23256  5228 pts/2    Ss   10:17   0:00          \_ -bash
ubuntu    5484  0.0  0.0  40252  3676 pts/2    R+   10:19   0:00              \_ ps fauxww
ubuntu    1165  0.0  0.0  76752  7660 ?        Ss   10:09   0:00 /lib/systemd/systemd --user
ubuntu    1175  0.0  0.0 193548  2296 ?        S    10:09   0:00  \_ (sd-pam)
root      4565  0.8  0.3 931880 31476 ?        Ssl  10:13   0:02 /usr/lib/snapd/snapd
root      5152  0.0  0.0   4504  1664 ?        Ss   10:13   0:00 /bin/sh /snap/lxd/11348/commands/daemon.start
root      5293  0.8  0.4 941012 39840 ?        Sl   10:13   0:02  \_ lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root      5282  0.0  0.0  95384  1384 ?        Sl   10:13   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root      5351  0.0  0.2 454688 19024 ?        Ssl  10:13   0:00 /usr/lib/lxd/lxd shutdown
`

**Comment by tomponline** [comment] 2020-03-30 10:23
Is this a freshly installed machine you're trying to upgrade, or was it previously setup with LXD?

**Comment by davigar15** [comment] 2020-03-30 10:24
It's a fresh machine with bionic. By default, it has LXD installed.

**Comment by tomponline** [comment] 2020-03-30 10:29
@davigar15 thanks, I've noticed this sometimes too.

Can you tell me if doing an `lxd init` before doing the `lxd.migrate` fixes the issue (i.e allows you to migrate cleanly?). Thanks

**Comment by davigar15** [comment] 2020-03-30 10:31
@tomponline You mean doing lxd init with the apt package, or with the snap.

My issue is that it gets stuck removing lxd. The migration has done properly.

**Comment by tomponline** [comment] 2020-03-30 10:32
@davigar15 yes, doing `lxd init` with the apt package before running `lxd.migrate`.

I've found that doing this, even with just a basic `lxd init` allows me to cleanly use `lxd.migrate`.

I wondered if you are perhaps hitting the same issue?

**Comment by tomponline** [comment] 2020-04-06 09:37
@stgraber I get this quite a lot when using LXD VMs with ubuntu:18.04 guest and upgrading to the snap package.

The general way I can see to reproduce it is to do as follows:

```
Launch fresh ubuntu:18.04 VM guest and enter shell
lxc # Just to start the apt version of lxd
snap install lxd
lxd.migate # this normally hangs
```

I've noticed that if I don't start the apt version of lxd by not running `lxc` then the `lxd.migrate` command succeeds fine.

I can see the process is hanging on `/usr/lib/lxd/lxd shutdown`:

```
root      2043  0.1  1.8  73412 18980 pts/1    S+   07:47   0:00 apt-get remove --purge --yes lxd lxd-client
root      2067  0.0  1.6  30960 16512 pts/2    Ss+  07:47   0:00 /usr/bin/dpkg --status-fd 26 --no-triggers --force-depends --remove lxd:amd64 lxd-client:amd64
root      2068  0.0  0.0   4640   924 pts/2    S+   07:47   0:00 /bin/sh /var/lib/dpkg/info/lxd.prerm remove
root      2075  0.0  0.5  65384  5568 pts/2    S+   07:47   0:00 /bin/systemctl stop lxd-containers.service
root      2076  0.0  1.8 379296 18516 ?        Ssl  07:47   0:00 /usr/lib/lxd/lxd shutdown
```

To debug this further I launched a fresh VM and before running `lxc` I modified the systemd unit to add the `--debug` flag for LXD.

I capture this debug when the `shutdown` command hung:

```
Apr 06 07:47:54 v1 systemd[1]: Stopping LXD - container startup/shutdown...
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=dbug msg=handling ip=@ method=PUT url=/internal/shutdown
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Asked to shutdown by API, shutting down containers"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=dbug msg="Cancel ongoing or future gRPC connection attempts"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Starting shutdown sequence"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Stopping REST API handler:"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg=" - closing socket" socket=/var/lib/lxd/unix.socket
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Stopping /dev/lxd handler"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg=" - closing socket" socket=/var/lib/lxd/devlxd/sock
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Closing the database"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=dbug msg="Dqlite: closing client"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=dbug msg="Stop database gateway"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=dbug msg="Stop raft instance"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=dbug msg="Dqlite: stopping event loop"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=dbug msg="Dqlite: event loop stopped"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Stopping REST API handler:"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Stopping /dev/lxd handler"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Stopping REST API handler:"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Stopping /dev/lxd handler"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Unmounting temporary filesystems"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Done unmounting temporary filesystems"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Saving simplestreams cache"
Apr 06 07:47:54 v1 lxd[1086]: t=2020-04-06T07:47:54+0000 lvl=info msg="Saved simplestreams cache"
```

Looking at the 3 series code this seems to be the end of the `Stop()` function (https://github.com/lxc/lxd/blob/lxd-3.0.3/lxd/daemon.go#L914-L927), so I am thinking perhaps the `defer stop()` in the `Start()` function is actually hanging (https://github.com/lxc/lxd/blob/lxd-3.0.3/lxd/main_daemon.go#L67).

**Comment by stgraber** [comment] 2020-04-06 13:32
Yeah, given it's in the removal path that this happens, I suspect the solution will be to detect this situation (shutdown running but no lxd) and just kill the process automatically...

**Comment by tomponline** [comment] 2020-04-06 13:35
@stgraber I'm not sure what you mean by "shutdown running but no lxd", do you think that LXD has indeed gone and its just the `lxd shutdown` API client that is hanging perhaps?

**Comment by stgraber** [comment] 2020-04-06 13:41
Yes, I don't see any actual `lxd` process in the `ps` output we've seen so far.

**Comment by tomponline** [comment] 2020-04-14 08:29
Closed by https://github.com/lxc/lxd-pkg-snap/commit/3972591270a1a11fc8d38586821f115876fc4bd4

**Closed by tomponline** 2020-04-14 08:29 UTC
